### ISSUE TITLE
Set-output command is deprecated

### ISSUE THREAD

**Issue by genarocolonel** [t-botz/aws-secrets-manager-read-action#187]
Hello,
The set-output command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Can you please update your GitHub Action please?

**Comment by t-botz** [comment]
Will do, thanks for flagging it!

**Comment by t-botz** [comment]
Fixed in v2.1.1
